---
- name: Install Apache and configure instances
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Create HTML index file
      template:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
